# Generated by Django 5.2.1 on 2025-06-03 22:53

import django.db.models.deletion
import kiosco.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('casino_name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('casino_street', models.CharField(max_length=250, verbose_name='Calle')),
                ('casino_number', models.CharField(max_length=250, verbose_name='Numero')),
                ('casino_between_streets', models.CharField(blank=True, max_length=250, null=True, verbose_name='Entre Calles')),
                ('casino_zip', models.CharField(max_length=250, verbose_name='Código Postal')),
                ('casino_suburb', models.CharField(max_length=250, verbose_name='Colonia')),
                ('casino_city', models.CharField(default='Tepic', max_length=250, verbose_name='Ciudad/Localidad')),
                ('casino_township', models.CharField(blank=True, max_length=250, null=True, verbose_name='Municipio')),
                ('casino_state', models.CharField(blank=True, max_length=250, null=True, verbose_name='Estado')),
                ('casino_reference', models.CharField(blank=True, max_length=250, null=True, verbose_name='Referencia')),
            ],
            options={
                'verbose_name': 'Casino',
                'verbose_name_plural': 'Casinos',
                'db_table': 'cat_casinos',
                'ordering': ['casino_name'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(help_text='En Proceso, Procesado, No Pagado,Pagado', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Estado del Pedido',
                'verbose_name_plural': 'Estados del Pedido',
                'db_table': 'cat_order_statuses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_fullname', models.CharField(max_length=250, verbose_name='Nombre Completo')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('customer_street', models.CharField(max_length=250, verbose_name='Calle')),
                ('customer_number', models.CharField(max_length=250, verbose_name='Numero')),
                ('customer_between_streets', models.CharField(blank=True, max_length=250, null=True, verbose_name='Entre Calles')),
                ('customer_zip', models.CharField(max_length=250, verbose_name='Código Postal')),
                ('customer_suburb', models.CharField(max_length=250, verbose_name='Colonia')),
                ('customer_city', models.CharField(max_length=250, verbose_name='Ciudad/Localidad')),
                ('customer_township', models.CharField(max_length=250, verbose_name='Municipio')),
                ('customer_state', models.CharField(max_length=250, verbose_name='Estado')),
                ('customer_reference', models.CharField(max_length=250, verbose_name='Referencia')),
                ('order_status', models.CharField(max_length=15, verbose_name='Estatus del Pedido')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Fecha de orden')),
                ('order_estimate_date', models.DateField(default=kiosco.models.next_date, verbose_name='Estimado de Entrega')),
                ('order_horario', models.CharField(default='', max_length=250, verbose_name='Horario de Entrega')),
                ('order_delivery_method', models.CharField(default='A domicilio', max_length=250, verbose_name='Forma de Entrega')),
                ('order_casino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_casino', to='kiosco.casino', verbose_name='Casino')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'tbl_hp_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderRecipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_size', models.CharField(max_length=250, verbose_name='Tamaño')),
                ('recipe_tier', models.CharField(max_length=250, verbose_name='Pisos')),
                ('recipe_shape', models.CharField(max_length=250, verbose_name='Forma/Figura')),
                ('recipe_flavor', models.CharField(max_length=250, verbose_name='Sabor')),
                ('recipe_fill', models.CharField(max_length=250, verbose_name='Relleno')),
                ('recipe_topping', models.CharField(max_length=250, verbose_name='Cubierta')),
                ('recipe_decoration', models.CharField(max_length=250, verbose_name='Decoraciones')),
                ('recipe_message', models.TextField(blank=True, null=True, verbose_name='Mensaje (Opcional)')),
                ('recipe_details', models.TextField(blank=True, null=True, verbose_name='Observaciones (Opcional)')),
                ('recipe_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('order_recipe', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='kiosco.order')),
            ],
            options={
                'verbose_name': 'Receta de Pedido',
                'verbose_name_plural': 'Recetas de Pedidos',
                'db_table': 'tbl_hp_orders_recipe',
                'ordering': ['id'],
            },
        ),
    ]
