# Generated by Django 5.2.6 on 2025-10-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_casino',
        ),
        migrations.RemoveField(
            model_name='orderrecipe',
            name='order_recipe',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='Casino',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderRecipe',
        ),
    ]
