# Generated by Django 5.2.1 on 2025-06-02 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_cobertura', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Tipo de Cobertura')),
            ],
            options={
                'verbose_name': 'Tipo de Cobertura',
                'verbose_name_plural': 'Tipos de Cobertura',
            },
        ),
        migrations.CreateModel(
            name='TipoForma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_forma', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Forma')),
                ('detalle_forma', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalle de la Forma')),
            ],
            options={
                'verbose_name': 'Tipo de Forma',
                'verbose_name_plural': 'Tipos de Forma',
            },
        ),
        migrations.CreateModel(
            name='TipoPan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_pan', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Pan')),
            ],
            options={
                'verbose_name': 'Tipo de Pan',
                'verbose_name_plural': 'Tipos de Pan',
            },
        ),
        migrations.CreateModel(
            name='TipoRelleno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_relleno', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Tipo de Relleno')),
            ],
            options={
                'verbose_name': 'Tipo de Relleno',
                'verbose_name_plural': 'Tipos de Relleno',
            },
        ),
        migrations.CreateModel(
            name='TipoTamano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tamano', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tamaño')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción (ej: porciones, dimensiones)')),
            ],
            options={
                'verbose_name': 'Tipo de Tamaño',
                'verbose_name_plural': 'Tipos de Tamaño',
                'ordering': ['nombre_tamano'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion_pan_base', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del Pan Base')),
                ('coberturas_disponibles', models.ManyToManyField(blank=True, related_name='categorias_con_esta_cobertura', to='configurador.tipocobertura', verbose_name='Coberturas Disponibles')),
                ('formas_disponibles', models.ManyToManyField(blank=True, related_name='categorias_con_esta_forma', to='configurador.tipoforma', verbose_name='Formas Disponibles')),
                ('panes_disponibles', models.ManyToManyField(blank=True, related_name='categorias_con_este_pan', to='configurador.tipopan', verbose_name='Panes Disponibles')),
                ('rellenos_disponibles', models.ManyToManyField(blank=True, related_name='categorias_con_este_relleno', to='configurador.tiporelleno', verbose_name='Rellenos Disponibles')),
                ('tamanos_disponibles', models.ManyToManyField(blank=True, related_name='categorias_con_este_tamano', to='configurador.tipotamano', verbose_name='Tamaños Disponibles')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='PastelConfigurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Final')),
                ('notas_adicionales', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasteles_configurados', to='configurador.categoria', verbose_name='Categoría')),
                ('coberturas_seleccionadas', models.ManyToManyField(blank=True, related_name='pasteles_con_estas_coberturas', to='configurador.tipocobertura', verbose_name='Coberturas Seleccionadas')),
                ('tipo_forma_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasteles_con_esta_forma', to='configurador.tipoforma', verbose_name='Forma Seleccionada')),
                ('tipo_pan_seleccionado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasteles_con_este_pan', to='configurador.tipopan', verbose_name='Pan Seleccionado')),
                ('rellenos_seleccionados', models.ManyToManyField(blank=True, related_name='pasteles_con_estos_rellenos', to='configurador.tiporelleno', verbose_name='Rellenos Seleccionados')),
                ('tipo_tamano_seleccionado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasteles_con_este_tamano', to='configurador.tipotamano', verbose_name='Tamaño Seleccionado')),
            ],
            options={
                'verbose_name': 'Pastel Configurado',
                'verbose_name_plural': 'Pasteles Configurados',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
