# Generated by Django 5.2.1 on 2025-07-27 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_quisco',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.CreateModel(
            name='CategoriaTiposCoberturaDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='configurador.categoria')),
                ('tipo_cobertura', models.ForeignKey(db_column='id_tipo_cobertura', on_delete=django.db.models.deletion.CASCADE, to='configurador.tipocobertura')),
                ('tipo_pan', models.ForeignKey(db_column='id_tipo_pan', on_delete=django.db.models.deletion.CASCADE, to='configurador.tipopan')),
            ],
            options={
                'verbose_name': 'Cobertura Disponible por Categoría',
                'verbose_name_plural': 'Coberturas Disponibles por Categoría',
                'db_table': 'categoria_tipos_cobertura_disponibles',
                'unique_together': {('categoria', 'tipo_pan', 'tipo_cobertura')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaTiposFormaDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='configurador.categoria')),
                ('tipo_forma', models.ForeignKey(db_column='id_tipo_forma', on_delete=django.db.models.deletion.CASCADE, to='configurador.tipoforma')),
            ],
            options={
                'verbose_name': 'Forma Disponible por Categoría',
                'verbose_name_plural': 'Formas Disponibles por Categoría',
                'db_table': 'categoria_tipos_forma_disponibles',
                'unique_together': {('categoria', 'tipo_forma')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaTiposPanDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='configurador.categoria')),
                ('tipo_pan', models.ForeignKey(db_column='id_tipo_pan', on_delete=django.db.models.deletion.CASCADE, to='configurador.tipopan')),
            ],
            options={
                'verbose_name': 'Pan Disponible por Categoría',
                'verbose_name_plural': 'Panes Disponibles por Categoría',
                'db_table': 'categoria_tipos_pan_disponibles',
                'unique_together': {('categoria', 'tipo_pan')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaTiposRellenoDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='configurador.categoria')),
                ('tipo_pan', models.ForeignKey(db_column='id_tipo_pan', on_delete=django.db.models.deletion.CASCADE, to='configurador.tipopan')),
                ('tipo_relleno', models.ForeignKey(db_column='id_tipo_relleno', on_delete=django.db.models.deletion.CASCADE, to='configurador.tiporelleno')),
            ],
            options={
                'verbose_name': 'Relleno Disponible por Categoría',
                'verbose_name_plural': 'Rellenos Disponibles por Categoría',
                'db_table': 'categoria_tipos_relleno_disponibles',
                'unique_together': {('categoria', 'tipo_pan', 'tipo_relleno')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaTiposTamanoDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica_corazon', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='configurador.categoria')),
                ('tipo_tamano', models.ForeignKey(db_column='id_tipo_tamano', on_delete=django.db.models.deletion.CASCADE, to='configurador.tipotamano')),
            ],
            options={
                'verbose_name': 'Tamaño Disponible por Categoría',
                'verbose_name_plural': 'Tamaños Disponibles por Categoría',
                'db_table': 'categoria_tipos_tamano_disponibles',
                'unique_together': {('categoria', 'tipo_tamano')},
            },
        ),
    ]
