# Generated by Django 5.2.1 on 2025-07-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0002_categoria_imagen_quisco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriatipostamanodisponibles',
            name='aplica_corazon',
        ),
        migrations.AddField(
            model_name='categoriatiposcoberturadisponibles',
            name='imagen_quisco',
            field=models.ImageField(blank=True, null=True, upload_to='coberturas/'),
        ),
        migrations.AddField(
            model_name='categoriatiposformadisponibles',
            name='imagen_quisco',
            field=models.ImageField(blank=True, null=True, upload_to='formas/'),
        ),
        migrations.AddField(
            model_name='categoriatipospandisponibles',
            name='imagen_quisco',
            field=models.ImageField(blank=True, null=True, upload_to='panes/'),
        ),
        migrations.AddField(
            model_name='categoriatiposrellenodisponibles',
            name='imagen_quisco',
            field=models.ImageField(blank=True, null=True, upload_to='rellenos/'),
        ),
    ]
