# Generated by Django 5.2.1 on 2025-07-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0003_remove_categoriatipostamanodisponibles_aplica_corazon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='imagen_quisco',
            new_name='imagen_quiosco',
        ),
    ]
