# Generated by Django 5.2.6 on 2025-09-13 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0004_rename_imagen_quisco_categoria_imagen_quiosco'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoColores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_color', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Colores')),
            ],
            options={
                'verbose_name': 'Tipo de Color',
                'verbose_name_plural': 'Tipos de Colores',
            },
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='coberturas_disponibles',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='formas_disponibles',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='panes_disponibles',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='rellenos_disponibles',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tamanos_disponibles',
        ),
        migrations.CreateModel(
            name='CategoriaTiposCoberturaColores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='configurador.categoria')),
                ('tipo_cobertura', models.ForeignKey(db_column='id_tipo_cobertura', on_delete=django.db.models.deletion.CASCADE, to='configurador.tipocobertura')),
                ('tipo_color', models.ForeignKey(db_column='id_tipo_color', on_delete=django.db.models.deletion.CASCADE, to='configurador.tipocolores')),
            ],
            options={
                'verbose_name': 'Color Disponible por Cubierta',
                'verbose_name_plural': 'Colores Disponibles por Cubierta',
                'db_table': 'categoria_tipos_cobertura_colores',
                'unique_together': {('categoria', 'tipo_cobertura', 'tipo_color')},
            },
        ),
    ]
