# Generated by Django 5.2.6 on 2025-09-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0005_tipocolores_remove_categoria_coberturas_disponibles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastelconfigurado',
            options={'verbose_name': 'Pastel Configurado', 'verbose_name_plural': 'Pasteles Configurados'},
        ),
        migrations.RemoveField(
            model_name='pastelconfigurado',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='pastelconfigurado',
            name='notas_adicionales',
        ),
    ]
