# Generated by Django 5.2.6 on 2025-09-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0006_alter_pastelconfigurado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pastelconfigurado',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
