# Generated by Django 5.2.6 on 2025-09-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0007_categoria_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasFestivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festivo', models.DateField()),
            ],
            options={
                'verbose_name': 'Dia Festivo',
                'verbose_name_plural': 'Dias Festivos',
                'db_table': 'dias_festivos',
            },
        ),
        migrations.AlterField(
            model_name='categoriatipospandisponibles',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, related_name='tipos_pan_disponibles', to='configurador.categoria'),
        ),
    ]
