# Generated by Django 5.2.6 on 2025-09-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0008_diasfestivos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horario Entrega',
                'verbose_name_plural': 'Horarios Entregas',
                'db_table': 'horario_entrega',
            },
        ),
    ]
