# Generated by Django 5.2.6 on 2025-09-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0009_horarioentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastelconfigurado',
            name='incluye',
            field=models.TextField(blank=True, null=True),
        ),
    ]
