# Generated by Django 5.2.6 on 2025-09-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0010_pastelconfigurado_incluye'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'db_table': 'extras',
            },
        ),
    ]
