# Generated by Django 5.2.6 on 2025-09-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0011_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastelconfigurado',
            name='monto_deposito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
