# Generated by Django 5.2.6 on 2025-09-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0012_pastelconfigurado_monto_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotamano',
            name='peso',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='pastelconfigurado',
            name='monto_deposito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
