# Generated by Django 5.2.6 on 2025-10-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0013_tipotamano_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastelconfigurado',
            name='medidas_pastel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastelconfigurado',
            name='peso_pastel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
