# Generated by Django 5.2.6 on 2025-10-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0014_pastelconfigurado_medidas_pastel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastelconfigurado',
            name='precio_final',
        ),
        migrations.AddField(
            model_name='pastelconfigurado',
            name='precio_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Base'),
        ),
        migrations.AddField(
            model_name='pastelconfigurado',
            name='precio_chocolate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Chocolate'),
        ),
    ]
