# Generated by Junie via automated edit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0015_remove_pastelconfigurado_precio_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastelconfigurado',
            name='rellenos_seleccionados',
        ),
        migrations.RemoveField(
            model_name='pastelconfigurado',
            name='coberturas_seleccionadas',
        ),
    ]
