# Generated by Django 5.2.7 on 2025-10-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0016_remove_pastelconfigurado_m2m_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaTiposTamanoDisponibles',
        ),
    ]
